# Generated by Django 4.1 on 2022-09-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='TipoDenuncia',
            field=models.CharField(choices=[('AB', 'Abandono'), ('MT', 'Maltrato')], default='Maltrato', max_length=20),
        ),
    ]
