# Generated by Django 4.1 on 2022-09-14 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerditusPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreMascotaExtraviada', models.CharField(max_length=30)),
                ('RazaMascotaExtraviada', models.CharField(max_length=15)),
                ('TipoMascotaExtraviada', models.CharField(max_length=15)),
                ('CaracteristicasMascota', models.CharField(max_length=200)),
                ('Donde', models.CharField(max_length=200)),
                ('cuando', models.DateTimeField()),
                ('contacto', models.IntegerField(max_length=10)),
                ('NombreDueñoMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
